config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :labels
  resources :favorites, only: [:create, :destroy]
  resources :pictures do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  belongs_to :user
  validates :content, presence: true, length: { maximum: 30 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/label.rb
class Label < ApplicationRecord
  validates :label_title, presence: true
  belongs_to :user
  has_many :picture_labels, dependent: :destroy
  has_many :pictures, through: :picture_labels, source: :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    has_many :comments, dependent: :destroy
    has_many :picture_labels, dependent: :destroy
    has_many :labels, through: :picture_labels, source: :label
    mount_uploader :image, ImageUploader
    validates :image_title, presence: true, length: { maximum: 30 }
    validates :image, presence: true
    validates :image_content, presence: true, length: { maximum: 255 }
end

app/models/picture_label.rb
class PictureLabel < ApplicationRecord
  belongs_to :picture
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  before_validation { email.downcase! }
  mount_uploader :user_image, ImageUploader
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :labels, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.build(comment_params)
    @comment.user_id = current_user.id
#binding.pry
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to picture_path(@picture), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @picture = @comment.picture
    if @comment.update(comment_params)
      redirect_to picture_path(@picture), notice: 'コメントの編集をしました！'
    else
      redirect_to picture_path(@picture), notice: 'コメントの更新が出来ませんでした'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format| 
        format.js { render :index }
        end
      end
    end

  private

  def comment_params
    params.require(:comment).permit(:picture_id,:content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to picture_path(favorite.picture.id), notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to picture_path(favorite.picture.id), notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if logged_in?
       redirect_to user_path(id: current_user.id)
     end
   end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :require_login

  def new
    @label = Label.new
    @labels = Label.all
  end

  def create
    @label = Label.new(label_params)
    @label.user_id = current_user.id

    unless @label.label_title.length > 11 || @label.label_title.empty?
      if @label.save
        redirect_to new_label_path, notice: 'ラベルを作成しました'
      else
        render 'new'
      end
    else
      redirect_to new_label_path, notice: '1文字以上10文字以内でお願いします。'
    end
  end

  def destroy
    @label = Label.find(params[:format])
    @label.destroy
    redirect_to new_label_path, notice: 'ラベルを削除しました'
  end

  private

  def label_params
    params.require(:label).permit(:label_title, :picture_id, :user_id)
  end

  def require_login
    unless logged_in?
      redirect_to root_path, notice: 'ログインしてください'
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :require_login
  
  def index
    @q = Picture.ransack(params[:q])
    @pictures = Picture.all.order('created_at DESC')
    if params[:q]
      @pictures = @q.result(distinct: true)
    end
  end

  def new
    @picture = Picture.new  
  end

  def show
    @picture = Picture.find(params[:id])
    @comments = @picture.comments
    @comment = @picture.comments.build
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
   
    #@favorites = Favorite.where(picture_id: @picture.id).all
    #binding.pry
  end

  def edit
    @picture = Picture.find(params[:id])
    unless current_user.id == @picture.user.id
      redirect_to picture_path(@picture.id), notice: '編集権限がありません'
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to picture_path(@picture.id), notice: '写真を投稿しました！'
    else
      render 'new'
    end
  end

  def update
    @picture = Picture.find(params[:id]) 
    if @picture.update(picture_params)
      redirect_to picture_path(@picture.id), notice: '写真の編集をしました！'
    else
      render :new
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
      redirect_to pictures_path, notice: '写真を削除しました'
  end

  private

  def picture_params
    params.require(:picture).permit(:image_title, :image_content, :image, :user_id, label_ids:[])
  end

  def require_login
    unless logged_in?
      redirect_to root_path, notice: 'ログインしてください'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def index
    render 'new'
  end

  def show
    @user = User.find(params[:id])
    @favorites = current_user.favorites.all
    unless current_user_page?
      redirect_to user_path(id: current_user.id)
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to @user, notice: '更新しました'
  else
    render 'edit'
  end
end

  private

  def user_params
    params.require(:user).permit(:name, :email, :user_image, :password, :password_confirmation)
  end

  def require_login
    unless logged_in?
      redirect_to root_path, notice: 'ログインしてください'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end

  def current_user_page?
    current_user.id == @user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_edit.html.erb
<body>
<div class="modal-dialog" role="document">
  <div class="modal-content">


<%= form_with(model: @comment, url: picture_comment_path(picture_id: @comment.picture_id, comment_id: @comment.id)) do |form| %>
  <div class="modal-header">
  <h5 class="modal-title">コメントの編集</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

  <div class="modal-body">
  <div class="field">
    <%= form.text_area :content, class: "comment_input" %>
  </div>
  <div class="actions">
    <%= form.submit "更新", class: "btn btn-lg btn-success" %>
    </div>
    </div>
  
<% end %>
</div>
</div>
</body>

app/views/comments/_form.html.erb
<%= form_with(model: [picture, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>：<br>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
  <%= form.submit "投稿する", class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each_with_index do |comment,i| %>
    <% if comment.id.present? %>
      <p><%= "#{h(i + 1)}" %> 投稿者：<%= comment.user.name %></p>
      <p>コメント：<%= comment.content %></p>
      <% if comment.user_id == current_user.id || picture.user_id == current_user.id %>
      <%= link_to '編集', "#{picture.id}/comments/#{comment.id}/edit", remote: true, class: "btn btn-lg btn-success" %>
      <%= link_to '削除', "#{picture.id}/comments/#{comment.id}", method: :delete, remote: true, class: "btn btn-lg btn-danger" %>
      <% end %>

      <div id="comment-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.js.erb
$("#comment-modal").html("<%= escape_javascript(render 'edit') %>")
$("#comment-modal").modal("show")

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.picture.comments, picture: @comment.picture }) %>")
$("textarea").val('')

app/views/labels/new.html.erb
<html>
<body>
<div>
<%= form_for @label do |form| %>
    <% if @label.errors.any? %>
      <div id="error_explanation">
        <h2><%= @label.errors.count %>件のエラーがあります。</h2>
        <% @label.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <div class="modal-header">
  <h5 class="modal-title">
  <div class = "label_new">
      <%= form_with(model: @label, local: true) do |form| %>
        <div class="label_title">
          <%= form.label :label_title %>
          <%= form.text_field :label_title %>
        <%= form.submit "登録する", class: 'btn btn-success'%>
      <% end %>
  </div>
  </h5>
  </div>

  <% @labels.each do |label| %>
    <div>
<ul>
<li class="label-grid">
    <label style="background-color: aquamarine"><%= label.label_title %></label><br>
    <% if label.user_id == current_user.id %>
    <td><%= link_to '削除',  new_label_path(label.id), method: :delete , class: 'btn btn-danger'%></td>
    <% else %>
    <br>
    <% end %>
    </li>
    </ul>
    <% end %>
</div>    
    </div>
    </body>
    </html>

app/views/pictures/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">

<%= form_with(model: @picture, local: true) do |form| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(picture.errors.count, "つのエラー") %> 下記理由によりエラーが発生しました！:</h2>
  
        <ul class="ten-non">
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% end %>
    
    <%= form_with(model: @picture, local: true) do |form| %>
      <div class="modal-header">
      <h5 class="modal-title">写真の編集</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <div class="field">
      <h2><%= form.label :image_title %></h2>
      <%= form.text_field :image_title, id: :picture_image_title %>
    </div>


    <div class="field">
      <h2><%= form.label :image_content %></h2>
      <%= form.text_field :image_content, id: :picture_image_content %>
    </div>

    <div class="field">
    <h2><%= form.label :image %></h2>
      <%= image_tag(@picture.image.url, :size =>'378x318') if @picture.image && @picture.image.url%><br>
  
      <%= form.file_field :image, id: :picture_image %>
      <%= form.hidden_field :image_cache %>
    </div>

    <% Label.all.each do |label|%>
      <%= form.check_box :label_ids, {multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id]%>
      <label style="background-color: aquamarine"><%= label.label_title %></label>
    <% end %>
  <br>
    <div class="modal-footer">
    <div class="actions">
      <%= form.submit "編集する", class: 'btn btn-success'%>
    </div>
    </div>
    <br>
  <% end %>
  </div>
  </div>

app/views/pictures/_form.erb
<%= form_with(model: picture, local: true) do |form| %>
    <% if picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(picture.errors.count, "つのエラー") %> 下記理由によりエラーが発生しました！:</h2>
  
        <ul class="ten-non">
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% end %>
    
    <%= form_with(model: @picture, local: true) do |form| %>

    <div class="field">
      <h2><%= form.label :image_title %></h2>
      <%= form.text_field :image_title, id: :picture_image_title %>
    </div>


    <div class="field">
      <h2><%= form.label :image_content %></h2>
      <%= form.text_field :image_content, id: :picture_image_content %>
    </div>

    <div class="field">
    <h2><%= form.label :image %></h2>
      <%= image_tag(@picture.image.url, :size =>'378x318') if @picture.image && @picture.image.url%><br>
  
      <%= form.file_field :image, id: :picture_image %>
      <%= form.hidden_field :image_cache %>
      
    </div>
  <br>
    <div class="actions">
      <%= form.submit %>
    </div>
    <br>
  <% end %>

app/views/pictures/_new.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">

<%= form_with(model: @picture, local: true) do |form| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(picture.errors.count, "つのエラー") %> 下記理由によりエラーが発生しました！:</h2>
  
        <ul class="ten-non">
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% end %>
    
    <%= form_with(model: @picture, local: true) do |form| %>
      <div class="modal-header">
      <h5 class="modal-title">写真の投稿</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <div class="field">
      <%= form.label :image_title %><br>
      <%= form.text_field :image_title, id: :picture_image_title %>
    </div>


    <div class="field">
      <%= form.label :image_content %><br>
      <%= form.text_area :image_content, id: :picture_image_content %>
    </div>

    <div class="field">
    <%= form.label :image %><br>
      <%= image_tag(@picture.image.url, :size =>'378x318') if @picture.image && @picture.image.url%><br>
  
      <%= form.file_field :image, id: :picture_image %><br>
      <%= form.hidden_field :image_cache %>
    </div>
    <br>
    <% Label.all.each do |label|%>
        <%= form.check_box :label_ids, {multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id]%>
        <label style="background-color: aquamarine"><%= label.label_title %></label>
      <% end %>
    <br>
    <br>
    <div class="modal-footer">
    <div class="actions">
      <%= form.submit "登録", class: 'btn btn-primary' %>
    </div>
    </div>
    <br>
  <% end %>
  </div>
  </div>

app/views/pictures/_show.html.erb
<div class="modal-dialog" role="document">
<div class="modal-content">
<body>
<div class="wrapper">
<header>

<div class="modal-header">
<h5 class="modal-title">写真</h5>
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
<%= link_to '詳細へ', @picture, class: 'btn btn-primary'%>
<% if @picture.user_id == current_user.id %>
<%= link_to '編集', edit_picture_path(@picture),remote: true, class: 'btn btn-success'%>
<div id="picture-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<% end %>

<h3 id="notice"><%= notice %></h3>
</header>

<br>
<br>
<h3>
  <%= @picture.image_title %>
</h3>
<p><%= image_tag @picture.image.url, :size =>'378x318'%>
</p>
<p>投稿者: 
<%= @picture.user.name %>さん
</p>
<p>コンテント: 
  <%= @picture.image_content %>
</p>

<% if @picture.labels.present? %>
<p>ラベル：
<% @picture.labels.each do |label| %>
  <label style="background-color: aquamarine"><%= label.label_title %></label>
<% end %></p>
<% else %>
<p>ラベル:none</p>
<% end %>

<br>


</body>
</div>
</div>

app/views/pictures/edit.html.erb
<%= form_with(model: @picture, local: true) do |form| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(picture.errors.count, "つのエラー") %> 下記理由によりエラーが発生しました！:</h2>
  
        <ul class="ten-non">
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% end %>
    
    <%= form_with(model: @picture, local: true) do |form| %>
      <div class="modal-header">
      <h5 class="modal-title">写真の編集</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <div class="field">
      <h2><%= form.label :image_title %></h2>
      <%= form.text_field :image_title, id: :picture_image_title %>
    </div>


    <div class="field">
      <h2><%= form.label :image_content %></h2>
      <%= form.text_field :image_content, id: :picture_image_content %>
    </div>

    <div class="field">
    <h2><%= form.label :image %></h2>
      <%= image_tag(@picture.image.url, :size =>'378x318') if @picture.image && @picture.image.url%><br>
  
      <%= form.file_field :image, id: :picture_image %>
      <%= form.hidden_field :image_cache %>
    </div>
    
    <% Label.all.each do |label|%>
        <%= form.check_box :label_ids, {multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id]%>
        <label style="background-color: aquamarine"><%= label.label_title %></label>
      <% end %>
  <br>
    <div class="actions">
      <%= form.submit "編集する", class: 'btn btn-success'%>
    </div>
    <br>
  <% end %>

app/views/pictures/edit.js.erb
$("#picture-modal").html("<%= escape_javascript(render 'edit') %>")
$("#picture-modal").modal("show")

app/views/pictures/index.html.erb
<html>
<body>
<div class='picture'>
<div class="modal-header">
<h5 class="modal-title">投稿写真リスト</h5>
<%= search_form_for @q do |f| %>
    <%= f.label :image_title_cont, "タイトル検索" %>
    <%= f.search_field :image_title_cont %>
    <%= f.submit "検索" %>
    <% end %>
</div>
    
<br>
<%= link_to '写真を投稿する',new_picture_path ,remote: true, class: 'btn btn-success' %>

<div> 
    <% @pictures.each do |picture| %>  
   
      <ul>
      <li class="grid">
      <p><%= picture.image_title %></p>
      <p><%= image_tag picture.image.url, :size =>'350x318'%></p>
        <p>投稿者: <%= picture.user.name %>さん</p>
        
        <p>本文: <%= picture.image_content %></p>

        <% if picture.labels.present? %>
        <p>ラベル：
        <% picture.labels.each do |label| %><label style="background-color: aquamarine"><%= label.label_title %></label>
        <% end %></p>
        <% else %>
        <p>ラベル：none</p>
        <% end %>
        <p><%= link_to '確認', picture ,remote: true, class: 'btn btn-primary'%>
        <% if current_user.id == picture.user.id %>
        <%= link_to "削除", picture, method: :delete, data: { confirm: "本当に削除してよろしいですか？","commit" => "削除する","cancel" => "やっぱりやめる",}, title: "削除の確認" , class: 'btn btn-danger'%>
      <% end %>
      </li>
      </ul>
  <% end %>
  </div>
  </div>
  <div id="picture-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  </body>
  </html>

app/views/pictures/new.js.erb
$("#picture-modal").html("<%= escape_javascript(render 'new') %>")
$("#picture-modal").modal("show")

app/views/pictures/show.html.erb
<html>
<body>
<div class="picture_show">
<% if @picture.user_id == current_user.id %>
<%= link_to '編集', edit_picture_path(@picture),remote: true, class: 'btn btn-success' %>
<div id="picture-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<% end %>
<%= link_to '一覧に戻る', pictures_path ,class: 'btn btn-primary'%>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

</header>
<br>
<br>
<h2>タイトル: 
  <%= @picture.image_title %>
</h2>
<p><%= image_tag @picture.image.url, :size =>'378x318'%>
</p>
<p>投稿者: <br>
<%= @picture.user.name %>さん
</p>
<p>コンテント: <br>
  <%= @picture.image_content %>
</p>

<% if @picture.labels.present? %>
<p>ラベル：<br>
<% @picture.labels.each do |label| %>
  <label style="background-color: aquamarine"><%= label.label_title %></label>
<% end %></p>
<% else %>
<p>ラベル：<br>none</p>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment, picture: @picture } %>
</div>


<div id="comments_area">
<%= render partial: 'comments/index', locals: { comments: @comments, picture: @picture } %>
</div>
</body>
</html>

app/views/pictures/show.js.erb
$("#picture-modal").html("<%= escape_javascript(render 'show') %>")
$("#picture-modal").modal("show")

app/views/users/_new.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="modal-header">
<h5 class="modal-title">アカウント登録</h5>
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>

<div class="modal-body">
<%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
  
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
  
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <br>
    <div class="modal-footer">
    <%= f.submit "アカウント登録", class: "btn-circle-fishy" %>
    </div>
  <% end %>
  </div>
</div>

app/views/users/edit.js.erb
$("#user-modal").html("<%= escape_javascript(render 'edit') %>")
$("#user-modal").modal("show")

app/views/users/new.html.erb
<html>
<body>
<div class='hero2'> 
<div class='cube'></div>
<div class='cube'></div>
<div class='cube'></div>
<div class='cube'></div>
<div class='cube'></div>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "つのエラー") %> 下記のエラーにより保存されませんでした。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>アカウント登録</h1>
<%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
  
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
  
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
  
    <%= f.submit "アカウント登録", class: "btn-social-long-insta" %>
  <% end %>

  <%= link_to 'ログイン', new_session_path, remote: true, class: "btn-social-long-insta" %>
  <div id="session-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

  </div>
</body>
</html>

app/views/users/show.html.erb
<html>
<body>
<div>
<div class="modal-header">
<h5 class="modal-title"><%= @user.name %>さんのページ</h5>
</div>
<p>メールアドレス:<br><%= @user.email %></p>
<% if @user.user_image.url %>
<p>ユーザーイメージ:<br><%= image_tag @user.user_image.url, :size =>'378x318'%></p>
<% else %>
<p>あなたの写真を投稿しよう！</p>
<% end %>

<%= link_to '編集', edit_user_path(@user) ,remote: true, class: 'btn btn-success'%> 

<div class="modal-header">
<h5 class="modal-title">お気に入り一覧</h5>
</div>
<% @favorites.each do |favorite| %>
<div> 
<ul>
<li class="favorite-grid">
    <div class= "field">
    <p><%= favorite.picture.image_title %><br></p>
    <p><%= image_tag favorite.picture.image.url, :size =>'378x318'%></p>
        <p>content：<%= favorite.picture.image_content %><br></p>
        <%= link_to '確認', favorite.picture ,remote: true,class: 'btn btn-primary'%>
</li>
</ul>
<% end %>
</div>
</div>

<div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="picture-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
</div>
</body>
</html>